### ISSUE TITLE
MIECD Dashboard: Table UI Design

### ISSUE THREAD

**Issue by oluwatobim** [OpenSRP/opensrp-web#105]
![image](https://user-images.githubusercontent.com/57088835/68955061-80424580-07c5-11ea-9ad2-c03cb3ef09dc.png)
Pagination should exist outside of table. And contents per page could be up to 10.

**Comment by FrankApiyo** [comment]
this seems to happen only for some browsers/screens... on it.

**Comment by hmakandi** [comment]
pagination confirmed as out of table and contents per page maintained at 3 for the solution.
