### ISSUE TITLE
MIECD Nutrition Calculations

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-web#117]
Height for age calculations

- [x] Where Height z columns is -2 then the child is categorized as Stunted
-2<Stunted

- [x] Weight for Age calculations when the Weight Z score value is as given
OVERWEIGHT >= 2
UNDERWEIGHT<=-2
SEVERE WASTING<=-3 OR SEVERE WASTING<115mm MUAC
-2<NORMAL<2
INAPPROPRIATELY FED if child_age<6 months AND Breastfeeding is not exclusive

**Comment by HusnaHariz** [comment]
This has been implemented in the nifi flows.
