### ISSUE TITLE
Backend Deployment

### ISSUE THREAD

**Issue by p-netm** [OpenSRP/opensrp-web#12]
There is currently the question of how the backend should be deployed, 

Soo opensrp-web needs a certain version of opensrp server that needs to work with the web-app i.e. the opensrp-web domain should not be CORS-blocked by the said opensrp server among other things.

**Comment by p-netm** [comment]
@githengi Need your comment on this or rather start a discussion on this.

**Comment by githengi** [comment]
The deployment can be easily done with the current OpenSRP playbooks. 

Is there a stage/development OpenSRP server provisioned for this.

**Comment by p-netm** [comment]
@moshthepitt

**Comment by p-netm** [comment]
@githengi I think this already resolved

**Comment by moshthepitt** [comment]
Should we close this then?

**Comment by githengi** [comment]
If Mpower were able to deploy OpenSRP server and the FE webapp is able to communicate with it then this can be closed

**Comment by p-netm** [comment]
ok
