### ISSUE TITLE
MIECD: Feedback Priority 2

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-web#132]
- [x] Need to tell the difference between mother's weight and child weight's for the weight graph. If the profile is for the mother, do not show the child's weight within as it distorts the data.

- [x]  The list for compartments should not have anybody that has given birth. It should only have current pregnancies.

- [x]  The nutrition compartment, you can click on totals which is good, but it shows 0 in locations drilldown. Please add the highlights to total column and allow for drilldown to show all categories under nutrition

- [x]  Capitalize the categories under nutrition

Stunted | Severe wasting | Overweight | Inappropriately fed
- [x] Make the column in Totals under nutrition wider to reflect the other columns

- [x] In nutrition compartment remove the "current symptoms" column and include Current Weight

- [x] Total Weight on the Nutrition page should be consistent as the others. That is we should have X Total Children under 5, and X Total Children Under 2. These should be clickable and allows for the drilldown. This means remove the Total Children Bubble

- [x]  Calculate the under 5 and under 2 based on dob

**Comment by FrankApiyo** [comment]
@hmakandi, about the first checkbox; currently we distinguish between mother and child using the `client_type` field. although for both the two client types**(woman and child)**, we have a single weight field... so an assumption is made that if the value of `client_type` is **woman** then the `weight` field also represents the weight of that **woman** and if the client type is **child** then the `weight` field represents the weight of that **child**. Is this assumption wrong and how can we distinguish between woman and child weight better?

@HusnaHariz

**Comment by HusnaHariz** [comment]
Yes, this is the way to distinguish the weights.
