### ISSUE TITLE
MIECD UAT Issues #1

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-web#154]
**Logface View**

- [x] For pregnancy registration (DKY) messages, when the risk category is NOT SET, simply leave it as GREY text without any box/border.  It should be greyed out, to show that it is not a categorization.

- [x] Risk categorization should be clickable and should take the user to the patient view.On click of the risk category, there should be a link to open the patient view.

- [x] In the logface remove SMS ID column

- [x] The Back in Compartment takes the user back to the very first compartment page . This should take you back to the previous page.

**Compartments View**

- [x] Within the compartments, change the category risk colors from orange to yellow 

- [x] At the end of the locations disaggregation(All the way to the commune), if there is no patient to show in the log the village level, display there is no patient in this record instead of leaving it empty. 

- [x] Within the compartment, the total should be clickable , and should follow similar actions to the risk categorizations. This means the total column should be highlighted and on click, the locations show according to the hierarchy

- [x] In the compartment table, the area for clicking should be bigger as people are not always specific with clicking just the name of the location.  This means the whole row should be clickable.

- [x] In Compartments, have the card that contains delivery due in one week to come before the deliveries due in 2 weeks. Preferred changes are to have the card with the 1 week first, then the 2 weeks, and then totals. Make the font bigger, and circles bigger. The circles should be clickable. Logface and compartments are both hard to see due to the size. Make the font size bigger. Consider having compartments (Total, 1 week, 2 weeks) broken down into 2 rows.  
<img width="1152" alt="Screenshot 2019-12-20 at 12 27 21" src="https://user-images.githubusercontent.com/18394882/72128309-8434b300-3383-11ea-8d52-1508e445b560.png">

**Comment by FrankApiyo** [comment]
@hmakandi, I'm going to split this issue into smaller issues in order to be able to more easily  make smaller PRs.

**Comment by hmakandi** [comment]
This is ok. Thanks @FrankApiyo

**Comment by hmakandi** [comment]
Closed the main issue and the child issues.
