### ISSUE TITLE
 Within the compartments, change the category risk colors from orange to yellow

### ISSUE THREAD

**Issue by FrankApiyo** [OpenSRP/opensrp-web#167]
Part of Issue #154

**Comment by FrankApiyo** [comment]
![Screenshot from 2020-01-15 09-55-16](https://user-images.githubusercontent.com/25260439/72411981-45d13680-377d-11ea-8c43-86977f76111b.png)
This is how yellow would look like

cc: @hmakandi

**Comment by FrankApiyo** [comment]
![Screenshot from 2020-01-15 09-55-26](https://user-images.githubusercontent.com/25260439/72412011-597c9d00-377d-11ea-8dc7-ff777d2dffaa.png)
This is a darker shade of yellow that looks more like gold.

**Comment by hmakandi** [comment]
@FrankApiyo  use the below for now 
#FFD300
