### ISSUE TITLE
Create Households Redux Store 

### ISSUE THREAD

**Issue by redoy11** [OpenSRP/opensrp-web#27]
Like the clients, issue #22  needs a separate file to define the Household reducer and related functions. 

- [ ] Create a new file under store/ducks to define the Household reducer.

- [ ] Use clients interface and endpoint since households endpoint is not ready.

- [ ] Create a reducer for Households.

- [ ] Create selectors to fetch a list of households from the store and also to fetch individual household information by id

- [ ] Add actions to add and remove households from store

**Comment by p-netm** [comment]
>     * Create a new redux store for Households

what xactly will this entail?, since we are going to be working with only the one store.

**Comment by redoy11** [comment]
I meant to say to create a separate file for the reducer of Households under store/ducks folder like the clients.ts. Writing "create a new redux store" does entitle something else. So sorry for the confusion. I am editing the description. Please take a look if there are any other issues!

**Comment by p-netm** [comment]
- [ ] Add action creators for Households fetching
- [ ] Modify clients dux to store households by Id to separate between other types of clients and families
- [ ] Add household specific selectors

**Comment by redoy11** [comment]
This issue is now redundant. An alternative solution to this issue can be resolved with issue #34.
