### ISSUE TITLE
Site characteristics should not be part of server settings

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-web#277]
Site characteristics are set on the device, not OpenSRP web. Remove these four:

![Screen_Shot_2020-07-20_at_11_36_18_AM](https://user-images.githubusercontent.com/3488986/87929386-41643e00-ca7e-11ea-80c9-bdc5cc8eb658.jpg)

**Comment by dubdabasoduba** [comment]
This is an OpenSRP server issue. I am working on it

**Comment by cafootitt** [comment]
This is done, closing.
