### ISSUE TITLE
Fix bugs in the action menu items

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-web#279]
When I log in and drill down to "Church Secondary School", I'm unable to change any of the pop characteristics using the Edit menu actions.

![Screen_Shot_2020-07-20_at_11_59_03_AM](https://user-images.githubusercontent.com/3488986/87931445-bbe28d00-ca81-11ea-8cb8-820eb9d52c0b.jpg)

**Comment by ciremusyoka** [comment]
This is caused by a change on the endpoint

**Comment by cafootitt** [comment]
This is fixed in app version 1.5.0
