### ISSUE TITLE
Design qa

### ISSUE THREAD

**Issue by rowo** [OpenSRP/opensrp-web#280]
- [ ] Breadcrumb nav - is this consistent with how this works/looks elsewhere? 
  <img width="527" alt="Screen Shot 2020-08-17 at 10 42 06 PM" src="https://user-images.githubusercontent.com/1584163/90464711-ee60c380-e0db-11ea-94f5-b743fa98d48e.png">
- [x] Last item in the breadcrumb should be blue since it's a link
  <img width="368" alt="Screen Shot 2020-08-17 at 10 46 22 PM" src="https://user-images.githubusercontent.com/1584163/90464724-f1f44a80-e0db-11ea-9c90-5266eee7e5e3.png">
- [x] These things should close when something is selected or if you click off. 
  <img width="234" alt="Screen Shot 2020-08-17 at 10 41 57 PM" src="https://user-images.githubusercontent.com/1584163/90464770-09cbce80-e0dc-11ea-968f-f24deff734b6.png">
- [x] This question icon should show a tooltip to explain how inheriting works. Someone can write that up, but it's generally that the higher level defines areas below if all areas below are set to "inherit setting", but if the child is changed, it takes precedence.
  <img width="152" alt="Screen Shot 2020-08-17 at 10 43 25 PM" src="https://user-images.githubusercontent.com/1584163/90464787-13edcd00-e0dc-11ea-9f4e-e5836faa33f4.png">
- [ ] Any reason why we can't do sortable columns on the table like seen on the other admin tables?
  <img width="1079" alt="Screen Shot 2020-08-17 at 10 45 07 PM" src="https://user-images.githubusercontent.com/1584163/90464808-210abc00-e0dc-11ea-893c-b30721ceae05.png">
- [x] The inherit setting button isn't working. It should change the row back to inheriting the setting (even if its the same as what the row is on currently, since it's a different setting).
  <img width="372" alt="Screen Shot 2020-08-17 at 10 45 39 PM" src="https://user-images.githubusercontent.com/1584163/90464841-2bc55100-e0dc-11ea-8bc2-a9e99531267d.png">
- [x] The inherit setting button is what the item should be default selected. But right now it doesn't even show up unless you change the setting. A "yes" inherited setting is not the same as a "yes" setting since if the parent changes, the inherited one will change.
  <img width="1033" alt="Screen Shot 2020-08-17 at 10 55 18 PM" src="https://user-images.githubusercontent.com/1584163/90465260-ff5e0480-e0dc-11ea-9efd-de7e26e69844.png">

**Comment by dubdabasoduba** [comment]
@rowo  the OpenSRP web team is to discuss the difference in the breadcrumbs used here and those on review web then update on the next cause of action.

**Comment by dubdabasoduba** [comment]
> - [ ] Any reason why we can't do sortable columns on the table like seen on the other admin tables?
  <img width="1079" alt="Screen Shot 2020-08-17 at 10 45 07 PM" src="https://user-images.githubusercontent.com/1584163/90464808-210abc00-e0dc-11ea-893c-b30721ceae05.png">

I have moved this to its own [issue](https://github.com/OpenSRP/opensrp-web/issues/287) due to the LOE estimated for the work.

**Comment by dubdabasoduba** [comment]
> - [ ] This question icon should show a tooltip to explain how inheriting works. Someone can write that up, but it's generally that the higher level defines areas below if all areas below are set to "inherit setting", but if the child is changed, it takes precedence.
  <img width="152" alt="Screen Shot 2020-08-17 at 10 43 25 PM" src="https://user-images.githubusercontent.com/1584163/90464787-13edcd00-e0dc-11ea-9f4e-e5836faa33f4.png">

This is related to the following [issue](https://github.com/OpenSRP/opensrp-web/issues/278)

**Comment by dubdabasoduba** [comment]
@rowo https://web.anc-stage.smartregister.org/ the issues addressed are marked.

**Comment by cafootitt** [comment]
All issues addressed apart from the breadcrumb one. Moving the breadcrumb to a separate issue.
