### ISSUE TITLE
Update README.md and start adding docs

### ISSUE THREAD

**Issue by cKellyDesign** [OpenSRP/opensrp-web#3]
We need to update the `README.md` to include basic project overview documentation. Let's keep most of our documentation in a `/docs` directory, with links to these pages/sections in the main `README.md`.

**Main Readme**
- [ ] Overview / summary of the project
- [ ] Collaboration / Contribution: (how to run it)

**/docs**
- [ ] Architecture: (how to **add** things)
- [ ] FE Standards (**how** to add things)
- [ ] Services/Utilities: (how to use things)
- [ ] Typescript: (how to write things)
- [ ] More?

**Comment by moshthepitt** [comment]
Really good typescript book: https://basarat.gitbooks.io/typescript/content/docs/getting-started.html

**Comment by p-netm** [comment]
### Proposed documentation structure
#### README
```
. overview
    .. summary
    .. Project structure(with links to docs)
. getting Started(installation and running)
. configuration
. testing
. collaboration/contributing
```
#### docs structure

```
. docs/
├── typescript and genreal conventions
├── Architecture
│   ├── components
│   │           .. how to add components
│   ├── containers
│   │           .. how to add containers
│   ├── services/utilities
│   │           .. how to add and use services/utilities
│   ├── components
│   │           .. how to add components
│   ├── store
│   │           .. adding reducers
│   │           .. adding actions
│   │           .. adding Selectors 
```

**Comment by moshthepitt** [comment]
This looks good to me.  Any thoughts @cKellyDesign ?

**Comment by moshthepitt** [comment]
@p-netm please also add a note about the linters that run with every commit

**Comment by moshthepitt** [comment]
I would also add something about https://www.freshconsulting.com/atomic-commits/

**Comment by cKellyDesign** [comment]
Structure looks good to me, nice and comprehensive
