### ISSUE TITLE
Extend Clients Redux for Households

### ISSUE THREAD

**Issue by redoy11** [OpenSRP/opensrp-web#34]
- [ ] Add action creators for Households fetching
- [ ] Add action creators for removal of Households from store
- [ ] Modify clients dux to store households by Id to separate between other types of clients and families
- [ ] Add household specific selectors 

@redoy11

_Originally posted by @p-netm in https://github.com/OpenSRP/opensrp-web/issues/27#issuecomment-525170285_

**Comment by p-netm** [comment]
closed by #37
