### ISSUE TITLE
Modyfing and styling the Navigation to look as in the mockups

### ISSUE THREAD

**Issue by p-netm** [OpenSRP/opensrp-web#41]
part of #39 

Style the navigation to the left sidebar, as shown in the mock up:

![image](https://user-images.githubusercontent.com/28119869/64009679-f917f680-cb20-11e9-8de9-c7b4b2d740a2.png)

**Comment by redoy11** [comment]
For the side navigation, I am planning to use the following library: https://github.com/alpertuna/react-metismenu . The demo can be found here: https://alpertuna.github.io/react-metismenu/#menu-2. 
@p-netm what are your thoughts?

**Comment by p-netm** [comment]
> https://github.com/alpertuna/react-metismenu

Concerns:
 - Seems like you may run into considerable overhead during styling, and seems like its not actively maintained. I feel for this we can have out own custom application.
[.](https://jsfiddle.net/ramnathv/mjt4s35x/)

**Comment by redoy11** [comment]
@p-netm  I agree that styling will be difficult. So I will make a custom one. 
In addition, should the side nave behave like accordions such as when selecting the Admin, only the Admin will remain open and others like Client Records or Reports will collapse? If so, I will like to use the following library- https://jedwatson.github.io/classnames/. The library is simple but seems effective to custom build an accordion.
