### ISSUE TITLE
QA MIECD dashboard

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-web#63]
- [x] When you login it it shows "Welcome Back" page. It should show this page when the user logs in
https://marvelapp.com/8ijdg2g/screen/61976965

- [x] Change the logo at the top to reflect the ones in the mockup

- [x] On the home page, add the images provided in the mockup for now as placeholders. These will change later to more realistic images.

- [x] The compartments on my screen overlap
<img width="970" alt="Screenshot 2019-10-22 at 12 25 56" src="https://user-images.githubusercontent.com/18394882/67364203-bf3efb80-f577-11e9-90ea-03e766fe774b.png">

- [x] This in the compartments should just be back as per the design. And Roboto-Medium , 16px
<img width="247" alt="Screenshot 2019-10-22 at 12 27 28" src="https://user-images.githubusercontent.com/18394882/67273566-62840800-f4c7-11e9-9df1-ee358616666e.png">

**Comment by moshthepitt** [comment]
> Add the language switcher - least priority

Let us create a different issue for this item.  We haven't yet decided on how to implement.

**Comment by moshthepitt** [comment]
@hmakandi ^^

**Comment by FrankApiyo** [comment]
>     * [ ]  When you login it it shows "Welcome Back" page. It should show this page when the user logs in
>       https://marvelapp.com/8ijdg2g/screen/61976965
> 
>     * [ ]  Change the logo at the top to reflect the ones in the mockup
> 
>     * [ ]  Add the language switcher - least priority
> 
>     * [ ]  On the home page, add the images provided in the mockup for now as placeholders. These will change later to more realistic images.
> 
>     * [ ]  The compartments on my screen overlap
> 
> 
> <img alt="Screenshot 2019-10-02 at 09 10 11" width="916" src="https://user-images.githubusercontent.com/18394882/67273467-2650a780-f4c7-11e9-8885-f4264e0a363c.png">
> 
>     * [ ]  This in the compartments should just be back as per the design. And Roboto-Medium , 16px
> 
> 
> <img alt="Screenshot 2019-10-22 at 12 27 28" width="247" src="https://user-images.githubusercontent.com/18394882/67273566-62840800-f4c7-11e9-9df1-ee358616666e.png">

@hmakandi I presume this is not the screenshot you intended to add here? Did you intend to add one showing the Compartments?

**Comment by hmakandi** [comment]
@FrankApiyo Thanks for the heads up, thankfully it wasn't my banking details

**Comment by hmakandi** [comment]
MLS not implemented yet and can be tracked in another issue. Closing this one.
