### ISSUE TITLE
To Monorepo or not?

### ISSUE THREAD

**Issue by moshthepitt** [OpenSRP/opensrp-web#7]
I'm thinking that it may be a good idea to consider restructuring this repo as follows (yes it is a monorepo):

```
opensrp-web/
|-- server/ (probably an express.js tiny backend)
|-- client/ (the CRA frontend code)
|-- packages/ (all the different OpenSRP modules)
```

Let me go through the parts above and their purpose:

- **server**: this would be a tiny tiny express.js backend that may be useful for a lot of things as previously discussed in https://github.com/onaio/reveal-frontend/issues/39 and https://github.com/onaio/reveal-frontend/issues/156.  The server will only be used when it is actually needed
- **client**: a really stripped down CRA ([create react app](https://facebook.github.io/create-react-app/)) that has the bare minimum structure needed for a client side react app (maybe just index.js and app.js) and loads the rest from `packages`.  It should be possible to deploy this independently (i.e. without the `server` above)
- **packages**: herein will be code for the various OpenSRP modules (structured similarly to [js-tools](https://github.com/onaio/js-tools)).  The idea is to make it possible for an OpenSRP web deployment to use only the modules that it needs in as modular and DRY a way as possible

### pros

- It would be easier to deploy OpenSRP web apps that have only the compiled javascript that they need and no more (this happens to be my main motivation in proposing this structure)
- It would be easier to set up the express.js mini server as the backend of the react app(s)
- Having everything in one repo makes the life of devs easier, arguably

### cons

- All the usual cons of having a monorepo

**Comment by githengi** [comment]
@moshthepitt I think this is a good idea.

**Comment by cKellyDesign** [comment]
@moshthepitt I like this a lot as well, a few questions off the bat:

1. Are you thinking of using Lerna like in js-tools (for packages or for everything?)
2. Moving modules into packages makes a lot of sense, how different would the **client** portion of the repo be from what was added from Reveal in #4?
3. Is this something we can do this week for hand off?

**Comment by moshthepitt** [comment]
@cKellyDesign nice!

1.  Yes I think we should use Lerna.  We might even want to publish the things in `packages`
2. I think we would remove more things, unless we are 100% sure they cant go elsewhere.  But I think we are close to what it would eventually look like, and we would probably keep the current reveal structure.  We would also need to aggressively monitor what goes into the `client` directory.
3. I dont think we can get the `server` part done this week but I would like us to have the `packages` and `client` set up.

**Comment by moshthepitt** [comment]
### Current thoughts

```
opensrp-web/
|-- server/ (probably an express.js tiny backend)
|-- clients/ (the individual CRA apps)
|-- packages/ (all the different OpenSRP modules)
```

Let me go through the parts above and their purpose:

- **server**: this would be a tiny tiny express.js backend that may be useful for a lot of things as previously discussed in https://github.com/onaio/reveal-frontend/issues/39 and https://github.com/onaio/reveal-frontend/issues/156.  The server will only be used when it is actually needed
- **clients**: individual CRA ([create react app](https://facebook.github.io/create-react-app/)) apps for different deployments of OpenSRP web
- **packages**: herein will be code for the various OpenSRP modules (structured similarly to [js-tools](https://github.com/onaio/js-tools)).  The idea is to make it possible for an OpenSRP web deployment to use only the modules that it needs in as modular and DRY a way as possible

**Comment by cKellyDesign** [comment]
I still think this is a powerful and scalable approach, and moving client CRAs into their own directories is an elegant solution to divergent code. Could we also manage those via Learn as well?

* **server**: Yes please, simple Express server will be lightweight and can do anything we need it to, make it so.
* **clients**: Here lives the business logic (aka customizations to the packages be shared among clients) coupled with any custom components / any other client-specific solutions.
* **packages**: Where the magic happens: Reusable and generic components/helpers/anything the clients needs. These packages should be written in a way that they can be extended upon or support middleware for client customization.

**Comment by cKellyDesign** [comment]
@moshthepitt how do you feel about using HerokuApp as a staging environment? We should be able to hook up the server folder to deploy automatically to try and reduce overhead around deployment.

**Comment by moshthepitt** [comment]
> Could we also manage those via Lerna as well?

We absolutely most certainly can, and I think we should :)

**Comment by moshthepitt** [comment]
> @moshthepitt @KipSigei how do you feel about using HerokuApp as a staging environment? We should be able to hook up the server folder to deploy automatically to try and reduce overhead around deployment.

I am ALL for this @cKellyDesign

**Comment by cKellyDesign** [comment]
> I am ALL for this @cKellyDesign

Booya, I think we can set it up so that it automatically generates new (name-spaced) instances when we create new branches/PRs too, and automatically update on every commit. This would be really really helpful when clients and leadership wants to see progress on things in development.

**Comment by craigappl** [comment]
@cKellyDesign , @moshthepitt Can you provide detail on the OpenSRP modules in the packages folder? How would you structure this for:

1) Generic components across projects (team management, user accounts, uploading forms, configuration)
2) Implementations (i.e. Reveal, BRAC, AfyaTek Tanzania)

**Comment by moshthepitt** [comment]
@craigappl 

> Generic components across projects (team management, user accounts, uploading forms, configuration)

These will go into the `packages` directory.  Ideally these should be published on [npm](https://www.npmjs.com) under the OpenSRP account.  Anyone who needs to use a "package" needs to install it and use it via npm.

> Implementations (i.e. Reveal, BRAC, AfyaTek Tanzania)

These will go into the `clients` directory.  Technically they don't even have to go here and could be independent repositories, but I think most implementations will live here, in the clients directory.  They will only contain implementation-specific code, and import everything else from the OpenSRP packages described in the paragraph before this one.

Does this sound good to you?

**Comment by KipSigei** [comment]
> @moshthepitt @KipSigei how do you feel about using HerokuApp as a staging environment? We should be able to hook up the server folder to deploy automatically to try and reduce overhead around deployment.

Yes @cKellyDesign I'm onboard with this idea.

**Comment by hmakandi** [comment]
@moshthepitt @cKellyDesign I agree with the approach of packages. The mention of installing them using npm makes reusability easily possible.

 How would the styling and assets bits be addressed? E.g. if for one package, the core web-app needs different styling, and assets e.g. logo and stuff. Will there be a structure to "deploy" the package assets and styling files? Will they overwrite the generic standard ones? Will someone have to edit some config file? How will this work?

**Comment by moshthepitt** [comment]
> How would the styling and assets bits be addressed? E.g. if for one package, the core web-app needs different styling, and assets e.g. logo and stuff. Will there be a structure to "deploy" the package assets and styling files? Will they overwrite the generic standard ones? Will someone have to edit some config file? How will this work?

Every "package" will come with default styling.  In the project that you use it, you will be able to add CSS files that override that default styling.
