### ISSUE TITLE
Add Compartments for NBC & PNC and Nutrition

### ISSUE THREAD

**Issue by FrankApiyo** [OpenSRP/opensrp-web#94]
- [x] Add Compartments for **NBC & PNC**
- [x] Add Compartments for **Nutrition**
- [x] Ensure that correct data is showed on the compartments page for the **pregnancy** module
- [x] Get VillageData component to show `SmsData` depending on the `risk_highlighter` URL parameter

- [x] Fix the badge types rendered by the risk coloring component

**Comment by FrankApiyo** [comment]
The `HierarchichalDataTable` component currently does not filter the data it shows correctly. For example, in the Pregnancy module, this component has to only show sms events whose type field has the value 'Pregnancy report` and within a certain time window. In order to implement this, I might take the following course of action:

1. Create an action creator that adds a set of filter parameters in the store and will be called every time we redirect to the `HierarchichalDataTable`
2. Create a selector that uses these filter parameters to get the correct data to be displayed by the `HierarchichalDataTable` component.
3. These parameters are removed from the store every time we  unmount the `HierarchichalDataTable` component, except when we redirect to the `PatientDetail` component. and also removed when we unmount the `PatientDetail` component

**Comment by hmakandi** [comment]
Implemented and confirmed
